import React, { useMemo, useState } from "react";
import { Alert, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { useWallet } from "@tetherto/wdk-react-native-provider";
import { Button } from "@/design-system/components/Button";
import { Card } from "@/design-system/components/Card";
import { Screen } from "@/design-system/components/Screen";
import { Text } from "@/design-system/components/Text";
import { Input } from "@/design-system/components/Input";
import { useSecureSession } from "@/hooks/useSecureSession";
import { logger } from "@/infrastructure/logging/logger";

export function WalletHomeScreen() {
  const navigation = useNavigation();
  const {
    balances,
    createWallet,
    isInitialized,
    refreshWalletBalance,
    unlockWallet,
    wallet,
  } = useWallet();
  const secureSession = useSecureSession();
  const [walletName, setWalletName] = useState("Main Wallet");
  const [isBusy, setIsBusy] = useState(false);

  const balanceRows = useMemo(
    () => balances?.list ?? [],
    [balances?.list],
  );

  async function handleUnlock() {
    setIsBusy(true);
    try {
      await secureSession.unlock();
      await unlockWallet();
    } catch (error) {
      logger.warn("Wallet unlock rejected", error);
    } finally {
      setIsBusy(false);
    }
  }

  async function handleCreateWallet() {
    setIsBusy(true);
    try {
      await createWallet({ name: walletName });
      await refreshWalletBalance();
    } catch (error) {
      logger.error("Create wallet failed", error);
      Alert.alert("Wallet creation failed", "Check WDK configuration and try again.");
    } finally {
      setIsBusy(false);
    }
  }

  if (!isInitialized) {
    return (
      <Screen>
        <Text variant="headlineSmall">Initializing wallet runtime</Text>
      </Screen>
    );
  }

  if (!wallet) {
    return (
      <Screen>
        <Text variant="headlineLarge">Create wallet</Text>
        <Text color="textMuted">
          A new recovery phrase is generated by WDK and stored through the
          secure wallet provider.
        </Text>
        <Input
          label="Wallet name"
          onChangeText={setWalletName}
          value={walletName}
        />
        <Button
          isLoading={isBusy}
          onPress={handleCreateWallet}
          title="Create Wallet"
        />
      </Screen>
    );
  }

  if (!secureSession.isUnlocked) {
    return (
      <Screen>
        <Text variant="headlineLarge">Wallet locked</Text>
        <Text color="textMuted">
          Biometric or device-passcode authentication is required before wallet
          data or signing actions are available.
        </Text>
        <Button isLoading={isBusy} onPress={handleUnlock} title="Unlock" />
      </Screen>
    );
  }

  return (
    <Screen scroll>
      <Text variant="headlineLarge">{wallet.name}</Text>
      <Card>
        <Text color="textMuted" variant="labelLarge">
          Portfolio
        </Text>
        <Text variant="displaySmall">
          {balanceRows.length === 0 ? "No balances" : `${balanceRows.length} assets`}
        </Text>
      </Card>
      <View style={{ flexDirection: "row", gap: 12 }}>
        <Button
          onPress={() => navigation.navigate("Receive" as never)}
          title="Receive"
          variant="secondary"
        />
        <Button
          onPress={() => navigation.navigate("Send" as never)}
          title="Send"
        />
      </View>
      <Button
        isLoading={balances?.isLoading}
        onPress={refreshWalletBalance}
        title="Refresh Balances"
        variant="outline"
      />
      {balanceRows.map((balance: { denomination?: string; value?: string }, index: number) => (
        <Card key={`${balance.denomination ?? "asset"}-${index}`}>
          <Text variant="titleSmall">{balance.denomination ?? "Asset"}</Text>
          <Text color="textMuted">{balance.value ?? "0"}</Text>
        </Card>
      ))}
    </Screen>
  );
}
